### ISSUE TITLE
Go製CLIのリリースについて考える

### ISSUE THREAD

**Issue by kyoh86** [kyoh86/dotfiles#82]
目下、GitHub ActionsとGoReleaser、git-vertagで比較的穏やかに過ごせている。
だが、ちょっと物足りない部分が出てきた。

- 最新のビルドステータスがSlackに通知されない
- git push && git vertag patch --push とかやって、build / testの落ちるtagを作ってしまいがち

もうちょっとイケてる感じにしたい。

**Comment by kyoh86** [comment]
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

これがあるからもうちょい上手く行くかも

**Comment by kyoh86** [comment]
- commit & push
  - run test
    - notify "releasable!"

- daily
  - notify "releasable!"

- kick release (with build, pre-release, patch, minor or major)
  - check status
  - add tag
  - test & build
  - push & upload

として、kick releaseがCIからもローカルからもできれば良いのか

**Comment by kyoh86** [comment]
さらに言えば

https://github.com/actions/create-release
https://github.com/actions/upload-release-asset

を使うと、より良さそう。

**Comment by kyoh86** [comment]
tagを計算するだけのやつもあるな
https://github.com/marketplace/actions/compute-tag

**Comment by kyoh86** [comment]
ただのrun:|でやったほうが良さそう。

inputはこれで渡せる
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#example-workflow-configuration

**Comment by kyoh86** [comment]
- actions/create-release
- actions/upload-release-asset

だと、homebrewに置けないからやっぱいいや

**Comment by kyoh86** [comment]
git-vertagを呼び出す部分をAction化しないとなー。
go runとかgo getでやると、go.modやgo.sumが更新されちゃってだるい
（一つの方法としては、tools.goを置くというのも手ではあるが…）

**Comment by kyoh86** [comment]
できた。

https://github.com/kyoh86/hoge/blob/master/.github/workflows/release-cli.yaml

```yaml
name: Relase CLI to the GitHub Release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor', 'patch' or 'release'.
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: ${{ github.event.inputs.method }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
```

**Comment by kyoh86** [comment]
check statusをどうやるかだなー

**Comment by kyoh86** [comment]
むしろ、check statusはどうでもよくて、artifactを受け取ったほうが良いのでは。
- push: master で test -> artifact@shaを入れる
- release で artifact@sha を見つけてきてそれを使ってゴニョゴニョする

**Comment by kyoh86** [comment]
artifactはそういえば同じWorkflow中でしか使用できないのだった。

**Comment by kyoh86** [comment]
```yaml
      - name: Validate Release
        uses: xembly/validate-workflow-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Github Actions, you do not need to create your own token
          workflow: build
          branch: main     #optional
          status: success  # optional
```

良さそう…だけど、branchの指定がいるのか。
master / mainの切替期だからつらいな

**Comment by kyoh86** [comment]
自分のリポジトリは全部mainにしよう。
はーめんどくせ

**Comment by kyoh86** [comment]
Pre-releaseうまく使いこなせないか…？
Publishするだけにすればいいのでは…？上手くいかんか？

**Comment by kyoh86** [comment]
- commit & push
  - run test
    - notify "releasable!"
- daily / weekly
  - notify "releasable!"
- kick pre-release (with build, pre-release, patch, minor or major)
  - add tag (pre-release)
  - release
  - "prereleased" events
    - add tag (release)
    - release

**Comment by kyoh86** [comment]
いや、意味ないや。
結局go testするのが良いな…時間的にはもったいないけど。

**Comment by kyoh86** [comment]
jobでdependして、ifでreleaseを外すのが良い気がする

**Comment by kyoh86** [comment]
できた

https://github.com/kyoh86/hoge/blob/4ae2b7fcc8ac42e05a0759f19be03fa6ac0c4eae/.github/workflows/cli.yaml

```yaml
name: Test and Release CLI to the GitHub Release
on:
  workflow_dispatch:
    inputs:
      method:
        description: |
          Which number to increment in the semantic versioning.
          Set 'major', 'minor', 'patch' or 'release'.
        required: true
  push:
    branches:
      - '*'
  pull_request:

env:
  GO_VERSION: 1.15

jobs:
  test:
    name: Test
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test Go
        run: go test -race ./...

  advanced:
    name: Cover and Dry Run Release
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    needs: test
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test Go
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true
          file: coverage.txt
      - name: Run GoReleaser (dry-run)
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --skip-publish --snapshot

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: test
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Bump-up Semantic Version
        uses: kyoh86/git-vertag-action@v1
        with:
          method: ${{ github.event.inputs.method }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: latest
          args: release --rm-dist
```
